version: '2.1'

services:
  keycloak:
    build: .
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: test
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: keycloak
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.6
    volumes:
      - ./data/mysql-v2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=keycloak --execute "SHOW DATABASES";'
      interval: 10s
      retries: 12
      
