version: '2.1'

services:
  keycloak:
    build: .
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: test
      KEYCLOAK_DEFAULT_THEME: tradelead
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: keycloak
      KEYCLOAK_IMPORT: /tmp/tradelead-realm.json
  mysql:
    image: mysql:5.6
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak
      
