AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CoreStack:
    Type: String
  KeycloakImage:
    Type: String
  KeycloakPassword:
    Type: String
  KeycloakUser:
    Type: String
  MySQLDbName:
    Type: String
  MySQLPass:
    Type: String
  MySQLUser:
    Type: String
Resources:
  KeycloakListenerRule:
    Properties:
      Actions:
        - TargetGroupArn: !Ref 'KeycloakTargetGroup'
          Type: forward
      Conditions:
        - Field: path-pattern
          Values:
            - /auth
            - /auth*
      ListenerArn: !ImportValue
        Fn::Sub: ${CoreStack}-ALB-Web-Listener
      Priority: 10
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
  KeycloakSecurityGroup:
    Properties:
      GroupDescription: Keycloak Service SG
      SecurityGroupIngress:
        - FromPort: 8080
          IpProtocol: tcp
          SourceSecurityGroupId: !ImportValue
            Fn::Sub: ${CoreStack}-LoadBalancer-SG-ID
          ToPort: 8080
      VpcId: !ImportValue
        Fn::Sub: ${CoreStack}-VPC-ID
    Type: AWS::EC2::SecurityGroup
  KeycloakService:
    Properties:
      Cluster: !ImportValue
        Fn::Sub: ${CoreStack}-ECS-Cluster
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: keycloak
          ContainerPort: 8080
          TargetGroupArn: !Ref 'KeycloakTargetGroup'
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !ImportValue
              Fn::Sub: ${CoreStack}-RDS-Access-SG-ID
            - !GetAtt 'KeycloakSecurityGroup.GroupId'
          Subnets:
            - !ImportValue
              Fn::Sub: ${CoreStack}-SubnetID
      TaskDefinition: !Ref 'KeycloakTask'
    Type: AWS::ECS::Service
  KeycloakTargetGroup:
    Properties:
      HealthCheckIntervalSeconds: 240
      HealthCheckPath: /auth/realms/main
      HealthCheckProtocol: HTTP
      HealthyThresholdCount: 5
      Port: '80'
      Protocol: HTTP
      TargetType: ip
      UnhealthyThresholdCount: 5
      VpcId: !ImportValue
        Fn::Sub: ${CoreStack}-VPC-ID
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
  KeycloakTask:
    Properties:
      ContainerDefinitions:
        - Environment:
            - Name: KEYCLOAK_USER
              Value: !Ref 'KeycloakUser'
            - Name: KEYCLOAK_PASSWORD
              Value: !Ref 'KeycloakImage'
            - Name: DB_VENDOR
              Value: mysql
            - Name: DB_ADDR
              Value: !ImportValue
                Fn::Sub: ${CoreStack}-MySQL-Address
            - Name: DB_PORT
              Value: !ImportValue
                Fn::Sub: ${CoreStack}-MySQL-Port
            - Name: DB_DATABASE
              Value: !Ref 'MySQLDbName'
            - Name: DB_USER
              Value: !Ref 'MySQLUser'
            - Name: DB_PASSWORD
              Value: !Ref 'MySQLPass'
            - Name: PROXY_ADDRESS_FORWARDING
              Value: 'true'
          Image: !Ref 'KeycloakImage'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub '${AWS::StackName}-KeycloakTask'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs
          MemoryReservation: '512'
          Name: keycloak
          PortMappings:
            - ContainerPort: 8080
      NetworkMode: awsvpc
    Type: AWS::ECS::TaskDefinition
Transform: AWS::Serverless-2016-10-31
